/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AAnchor: typeof import('ant-design-vue/es')['Anchor']
    AAvatar: typeof import('ant-design-vue/es')['Avatar']
    ACard: typeof import('ant-design-vue/es')['Card']
    ACardMeta: typeof import('ant-design-vue/es')['CardMeta']
    ACarousel: typeof import('ant-design-vue/es')['Carousel']
    ACol: typeof import('ant-design-vue/es')['Col']
    AFlex: typeof import('ant-design-vue/es')['Flex']
    AImage: typeof import('ant-design-vue/es')['Image']
    ALayout: typeof import('ant-design-vue/es')['Layout']
    APagination: typeof import('ant-design-vue/es')['Pagination']
    APlayer: typeof import('./src/components/APlayer.vue')['default']
    ARow: typeof import('ant-design-vue/es')['Row']
    ASpace: typeof import('ant-design-vue/es')['Space']
    ASpin: typeof import('ant-design-vue/es')['Spin']
    ATag: typeof import('ant-design-vue/es')['Tag']
    BilibiliLike: typeof import('./src/components/home/bilibili-like.vue')['default']
    CusSpin: typeof import('./src/components/cus-spin.vue')['default']
    DefaultLayout: typeof import('./src/components/layout/default-layout.vue')['default']
    DynamicIcon: typeof import('./src/components/dynamic-icon.vue')['default']
    Header: typeof import('./src/components/layout/header.vue')['default']
    Music163History: typeof import('./src/components/home/music163-history.vue')['default']
    NotionPage: typeof import('./src/components/notion-page.vue')['default']
    NotionPageClient: typeof import('./src/components/notion-page/notion-page-client.vue')['default']
    RandomCover: typeof import('./src/components/post/random-cover.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
